import { StoryItem } from './types';

const publicBaseUrl = process.env.PUBLIC_URL || '';

export const s03e01Story: StoryItem[] = [
  { text: '...', image: `${publicBaseUrl}/avatar.png` },
  { text: 'Kdo jsi?', image: `${publicBaseUrl}/avatar.png` },
  { text: 'V nitru duše cítím úzkost.', image: `${publicBaseUrl}/avatar.png` },
  { text: 'Mám pocit, že tě znám.', image: `${publicBaseUrl}/avatar.png` },
  { text: 'Tvá postava patří muži, kterého znám ze skoro zapomenutém snu.', image: `${publicBaseUrl}/avatar.png` },
  { text: 'A přesto vím, že tě neznám.', image: `${publicBaseUrl}/avatar.png` },
  { text: '', image: `${publicBaseUrl}/karlopolis.png` },
  { text: 'Co je to za místo?', image: `${publicBaseUrl}/avatar.png` },
  { text: 'Proč mě při pohledu do odlesků na hladině naplňuje děs?', image: `${publicBaseUrl}/karlopolis.png` },
  { text: 'Vše uvnitř mě se svírá a kříčí "Uteč!"', image: `${publicBaseUrl}/karlopolis.png` },
  { text: 'Ale já přesto s jistotou vím, že můj osud leží zde?', image: `${publicBaseUrl}/karlopolis.png` },
  { text: '', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '...', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'Kde to jsem?', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '...', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'Co se stalo?', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '<zvuk kroků>', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '...', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'Vstávej Karle.', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '...', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'Kdo je Karel?', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '...', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'Ošklivě jsi se praštil do hlavy.', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'Kdo je Karel?', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'Ty jsi Karel.', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'já...?', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '...já jsem Karel!', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'a sloužím lidem...', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'Karlopolis!', image: `${publicBaseUrl}/karel_clean.png` },
  { text: '', image: `${publicBaseUrl}/karel_clean.png` },
  { text: '', image: `${publicBaseUrl}/evzen_open_eyes.png` },
  { name: '{Evžen}?', image: `${publicBaseUrl}/evzen_open_eyes2.png` },
  { text: 'Ukaž, pomůžu ti se postavit na nohy.', image: `${publicBaseUrl}/evzen.png` },
  { text: 'Dávej pozor a pojď se mnou.', image: `${publicBaseUrl}/evzen.png` },
  { text: '', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'Silvestr s Karlem Sedláčkem 2026.', image: `${publicBaseUrl}/recursion.png` },
  { text: '', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'S03E01 - Karel poznává svořitele', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '<dunění těžkých psací strojů>', image: `${publicBaseUrl}/blackscreen.png` },
  { text: 'Ty máš umpalumpy?', image: `${publicBaseUrl}/karel_clean.png` },
  { text: '<zvuk Evženova smíchu>', image: `${publicBaseUrl}/evzen5.png` },
  { text: 'Ne, to jsou jen svobodní lidé Karlopolis.', image: `${publicBaseUrl}/evzen.png` },
  { text: 'Jejich hloupé nápady jim nepřekáží v tom co dělají.', image: `${publicBaseUrl}/evzen.png` },
  { text: 'A to jen díky tobě Karle.', image: `${publicBaseUrl}/evzen2.png` },
  { text: 'Okey... asi si je potřebuju připomenout?', image: `${publicBaseUrl}/karel_clean.png` },
  { text: 'Ale jistě!', image: `${publicBaseUrl}/evzen.png` },
  { text: 'Tohle je Tadedáš.', image: `${publicBaseUrl}/evzen2.png` },
  { name: '{Tadedáš}.', image: `${publicBaseUrl}/tadeas.png` },
  { text: 'Tadedáš je přímočarej.', image: `${publicBaseUrl}/tadeas.png` },
  { text: 'Tohle je Ondra.', image: `${publicBaseUrl}/evzen3.png` },
  { name: '{Ondra}.', image: `${publicBaseUrl}/ondra.png` },
  { text: 'O Ondrovi ještě uslyšíš.', image: `${publicBaseUrl}/ondra.png` },
  { text: 'Dalibora si musíš pamatovat. Jsme rádi, že se k nám vrátil.', image: `${publicBaseUrl}/evzen2.png` },
  { name: '{Dalibor}.', image: `${publicBaseUrl}/dalibor.png` },
  { text: 'Tohle je Klátra.', image: `${publicBaseUrl}/evzen3.png` },
  { text: '', image: `${publicBaseUrl}/klatra.png` },
  { name: '{Klátra} tu je, aby tu byl někdo schopnej.', image: `${publicBaseUrl}/klatra.png` },
  { text: 'A tohle je !.', image: `${publicBaseUrl}/karel_empty.png` },
  { name: '{Faktoriál} je velmi zodpovědný...', image: `${publicBaseUrl}/fak1.png` },
  { text: '...je zodpovědný za většinu našich problémů.', image: `${publicBaseUrl}/fak2.png` },
  { text: '...', image: `${publicBaseUrl}/karel_clean.png` },
  { text: '...nějak se mi z toho točí hlava...', image: `${publicBaseUrl}/karel_clean.png` },
  { text: 'Ale to je pochopitilné Karle...', image: `${publicBaseUrl}/evzen.png` },
  { text: '...tohle si nemáš pamatovat.', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '<zvuk ticha>', image: `${publicBaseUrl}/blackscreen.png` },
  { text: '', image: `${publicBaseUrl}/blackscreen.png` },
];
